In [1]:
import pandas as pd
import requests
import json
from pandas.io.json import json_normalize
from datetime import datetime
from pathlib import Path
import os
import time

In [2]:
#This gets the parent directory of the current directory
current = os.getcwd()
path = Path(current)
repo_folder = path.parent
print(repo_folder)

path_to_newValues = str(repo_folder)+'\\data\\DailyValues'
print(path_to_newValues)

C:\Users\Russell\OneDrive - Marist College\School\Spring 2020\DATA 450 Data Capping\Repository
C:\Users\Russell\OneDrive - Marist College\School\Spring 2020\DATA 450 Data Capping\Repository\data\DailyValues

In [3]:
dfAAPL = pd.read_csv(path_to_newValues+'\\AAPLDaily.csv')

In [4]:
dfAAPL.time = pd.to_datetime(dfAAPL.time)

In [ ]:
percentChangeList = []
for row in dfAAPL.time:
    print(dfAAPL[[dfAAPL==row]])

In [25]:
dfAAPL['avg'] = (dfAAPL.open + dfAAPL.close)/2

In [5]:
dfAAPL['percentChange'] = dfAAPL['close'].pct_change(periods=-1)
dfAAPL['percentVol'] = dfAAPL['volume'].pct_change(periods=-1)

In [7]:
dfAAPL

,close,open,high,time,volume,low,percentChange,percentVol
0,323.62,320.00,324.57,2020-02-19,23441259,320.00,0.014483,-0.379077
1,319.00,315.36,319.75,2020-02-18,37752293,314.61,-0.018311,0.884934
2,324.95,324.73,325.98,2020-02-14,20028447,322.85,0.000246,-0.154450
3,324.87,324.19,326.22,2020-02-13,23686892,323.35,-0.007121,-0.166910
4,327.20,321.47,327.22,2020-02-12,28432573,321.47,0.023748,0.205752
...,...,...,...,...,...,...,...,...
5027,115.20,117.31,119.12,2000-02-24,3361000,111.75,-0.009032,-0.204328
5028,116.25,113.23,119.00,2000-02-23,4224100,111.00,0.021439,0.120302
5029,113.81,110.12,116.94,2000-02-22,3770500,106.69,0.023011,0.809001
5030,111.25,114.62,115.37,2000-02-18,2084300,110.87,-0.031514,-0.193632
5031,114.87,115.19,115.50,2000-02-17,2584800,113.12,NaN,NaN